name: my First WorkFlow 

on:
  push:
    branches: [ "main"]


jobs:

  workflow:
    runs-on: ubuntu-latest

    steps:
    - name: echo hello world
      run: echo "hello world"

    - name: Run ls -al
      run: ls -al

    - name: enviroment vaiables
      run: echo $GITHUB_SHA 
    
    - name: Echo mySecret
      run: |
       echo ${{ secrets.MY_NAME}}
       echo ${{ secrets.MY_HOBBY}}

