name: my First WorkFlow 

on:
  push:
    branches: [ "main"]


jobs:

  workflow:
    runs-on: ubuntu-latest

    steps:
    - name: echo hello world
      run: echo "hello world"
      
    - name: Run ls -al
      run: ls -al
